apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocdcicd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocdcicd
  template:
    metadata:
      labels:
        app: argocdcicd
    spec:
      containers:
      - name: argocdcicd
        image: yuumassj/argocdtest:1ae5b60fa52d517b7258c77b788ba09604dc651b
        ports:
        - containerPort: 8080
