apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocdcicd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocdcicd
  template:
    metadata:
      labels:
        app: argocdcicd
    spec:
      containers:
      - name: argocdcicd
        image: yuumassj/argocdtest:ec5567d0410ecf22d03f0b0dd46e5aa369129c2a
        ports:
        - containerPort: 8080
