apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocdcicd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ArgoCD_CICD_App
  template:
    metadata:
      labels:
        app: ArgoCD_CICD_App
    spec:
      containers:
      - name: argoconteneur
        image: yuumassj/argocdtest:latest
        ports:
        - containerPort: 8080
