apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocdcicd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocdcicd
  template:
    metadata:
      labels:
        app: argocdcicd
    spec:
      containers:
      - name: argocdcicd
        image: yuumassj/argocdtest:a1c9f68fd5bf932e010b7d287759553c7b63de91
        ports:
        - containerPort: 8080
