name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/argocdtest:${GITHUB_SHA} .

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/argocdtest:${GITHUB_SHA}

      # - name: Checkout code for the update
      #   uses: actions/checkout@v4
      #   with:
      #     ref: main
      
      # - name: Update Deployment Image Tag
      #   run: |
      #     sed -i "s|${{ secrets.DOCKERHUB_USERNAME }}/reactcicd:.*|${{ secrets.DOCKERHUB_USERNAME }}/reactcicd:${GITHUB_SHA}|g" ./cicd/reactCICD/deployment/deployment.yaml
      #     git config --global user.email "action@github.com"
      #     git config --global user.name "GitHub Action"
      #     git add .
      #     git commit -am "Update image tag to ${GITHUB_SHA}" || echo "No changes to commit"
      #     git push origin main

