name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/argocdtest:${GITHUB_SHA}

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/argocdtest:${GITHUB_SHA}

      - name: Checkout code for the update
        uses: actions/checkout@v3
        with:
          ref: master