name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t argocdtest .

      - name: Log into Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag and Push Docker image
        run: |
          docker tag argocdtest ${{ secrets.DOCKERHUB_USERNAME }}/argocdtest:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/argocdtest:latest

      - name: Trigger ArgoCD deployment
        uses: ilackarms/argocd-notifications@master
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
          ARGOCD_APP: argocicd
          ARGOCD_NAMESPACE: default
          ARGOCD_PROJECT: default
          ARGOCD_SYNC_OPTIONS: '{"prune":true}'
          ARGOCD_MANIFEST_GENERATION: 'v1'